### ISSUE TITLE
Remove need for passing the config file as a cli argument

### ISSUE THREAD

**Issue by jmeaster30** [jmeaster30/simpledns#15]
I would like to have it so the config file is searched for at certain paths in a specific priority.

Then, if it cant find a config file, we generate the file with the current default config yaml.

Order to check the paths should be:
1. `./dns.config.yaml`
2. `~/.config/simpledns/dns.config.yaml`
3. `/etc/simpledns/dns.config.yaml`

Default path should be `~/.config/simpledns/dns.config.yaml`

**Comment by witchofthewires** [comment]
#16 has been submitted to resolve
